// <auto-generated />
using System;
using AradaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuAppAPI.Migrations.AuthDb
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20241116212339_InitialInitAuthDb")]
    partial class InitialInitAuthDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MenuAppAPI.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "b98bbc8-e2c0-4ecd-9f33-dd46ccb4fde4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "abadef32-7f10-4234-9595-dd6a6a788290",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "HUNGRYALAA",
                            PasswordHash = "AQAAAAIAAYagAAAAEPtLvedFMKEoPGjkndVRpqvtEDM1yz+kyIhTfKYlXgZH3ZPFqq0NqEGv+wsnTYWXvQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "41af9f6e-089a-4d40-9410-60ecd236d2d5",
                            TwoFactorEnabled = false,
                            UserName = "HungryAlaa"
                        },
                        new
                        {
                            Id = "55a1bccc-0507-4c89-a818-0b4a0bce99eb",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c2034c23-0b59-464a-8c55-01c798770169",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "HUNGRYAHMED",
                            PasswordHash = "AQAAAAIAAYagAAAAENGQXElQV1khqm23XMI+52GhiM4fZ5mnzkSOM2Yag0zinwY9cUcJ854PjDime8X+ew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "37e61c04-50ea-44d3-9385-d12c14aba039",
                            TwoFactorEnabled = false,
                            UserName = "HungryAhmed"
                        },
                        new
                        {
                            Id = "abea63e9-3bfb-4564-9a61-5723920767c8",
                            AccessFailedCount = 0,
                            BranchId = 1,
                            ConcurrencyStamp = "a9f44ec5-55ce-4730-93e9-47c0ca5c6d00",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "BESIKTASUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAECDP4FzEXfA2MAyr/tyIne2JOC/XqwkR+9aopeGIl1KihemPOP7eMuFSlzgzkHvo5A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1dc390b8-b108-4e8b-9a6c-651761ee83d7",
                            TwoFactorEnabled = false,
                            UserName = "Besiktasuser"
                        },
                        new
                        {
                            Id = "8552276d-5fed-4ab9-8513-e2e5b868cf45",
                            AccessFailedCount = 0,
                            BranchId = 3,
                            ConcurrencyStamp = "9ff1bc64-e669-40b5-9c0a-2fa65ab53144",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "BATISEHIRUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEPn/xmdZ9DxhQ1G52x7+awcHiT0PFQQOXYWvbs2kD6vvCD2IzPL18oaey8u5/RprvA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2ef97330-c50b-4bc9-95d9-130ca61681eb",
                            TwoFactorEnabled = false,
                            UserName = "Batisehiruser"
                        },
                        new
                        {
                            Id = "a63bbcf0-da35-4d1b-8109-47ab589a083c",
                            AccessFailedCount = 0,
                            BranchId = 2,
                            ConcurrencyStamp = "519e3551-c36b-4199-915e-f890f443a1a8",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "MASLAKUSER",
                            PasswordHash = "AQAAAAIAAYagAAAAEMCULVDuUB7OWTWgNOtpTVjylLczV3zBH5QsgAEnwoiLA9FefDY9TXeJcXWdjRqIxg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ec73ed4b-a2a5-40fd-9dd6-5afdea07efda",
                            TwoFactorEnabled = false,
                            UserName = "Maslakuser"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f59b1d3c-8245-4250-920c-f94e70cbaefa",
                            ConcurrencyStamp = "f59b1d3c-8245-4250-920c-f94e70cbaefa",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "bf50746d-89a1-4260-912c-beb0ac4562b5",
                            ConcurrencyStamp = "bf50746d-89a1-4260-912c-beb0ac4562b5",
                            Name = "Cashier",
                            NormalizedName = "CASHIER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "b98bbc8-e2c0-4ecd-9f33-dd46ccb4fde4",
                            RoleId = "f59b1d3c-8245-4250-920c-f94e70cbaefa"
                        },
                        new
                        {
                            UserId = "55a1bccc-0507-4c89-a818-0b4a0bce99eb",
                            RoleId = "f59b1d3c-8245-4250-920c-f94e70cbaefa"
                        },
                        new
                        {
                            UserId = "abea63e9-3bfb-4564-9a61-5723920767c8",
                            RoleId = "bf50746d-89a1-4260-912c-beb0ac4562b5"
                        },
                        new
                        {
                            UserId = "8552276d-5fed-4ab9-8513-e2e5b868cf45",
                            RoleId = "bf50746d-89a1-4260-912c-beb0ac4562b5"
                        },
                        new
                        {
                            UserId = "a63bbcf0-da35-4d1b-8109-47ab589a083c",
                            RoleId = "bf50746d-89a1-4260-912c-beb0ac4562b5"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MenuAppAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MenuAppAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenuAppAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MenuAppAPI.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
