// <auto-generated />
using System;
using AradaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuAppAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241207194516_initial Migration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AradaAPI.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("locationUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("AradaAPI.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CategoryOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AradaAPI.Models.Coupons", b =>
                {
                    b.Property<int>("couponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("couponID"));

                    b.Property<int>("afterDiscountPrice")
                        .HasColumnType("int");

                    b.Property<string>("couponCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("menuItemId")
                        .HasColumnType("int");

                    b.HasKey("couponID");

                    b.HasIndex("menuItemId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("AradaAPI.Models.Videos", b =>
                {
                    b.Property<int>("videoID")
                        .HasColumnType("int");

                    b.Property<string>("videoUrlAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("videoUrlEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("videoUrlTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("videoID");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PriceAr")
                        .HasColumnType("int");

                    b.Property<int>("PriceEn")
                        .HasColumnType("int");

                    b.Property<int>("PriceTr")
                        .HasColumnType("int");

                    b.Property<int?>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("imageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("isVisible")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("categoryId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("AradaAPI.Models.Coupons", b =>
                {
                    b.HasOne("MenuItem", "menuItem")
                        .WithMany()
                        .HasForeignKey("menuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menuItem");
                });

            modelBuilder.Entity("AradaAPI.Models.Videos", b =>
                {
                    b.HasOne("MenuItem", "menuItem")
                        .WithOne("Video")
                        .HasForeignKey("AradaAPI.Models.Videos", "videoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menuItem");
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.HasOne("AradaAPI.Models.Categories", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("categoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AradaAPI.Models.Categories", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.Navigation("Video")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
