// <auto-generated />
using System;
using AradaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenuAppAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241116212254_InitialInitAppDb")]
    partial class InitialInitAppDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MenuAppAPI.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("locationUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("MenuAppAPI.Models.Categories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CategoryImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CategoryOrder")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("MenuAppAPI.Models.Offers", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("descriptionAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("descriptionEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("descriptionTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("isVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("offerOrder")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("MenuAppAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StudentEmail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.Property<bool>("isRated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("isStudent")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("totalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MenuAppAPI.Models.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("itemPrice")
                        .HasColumnType("int");

                    b.Property<int>("menuItemId")
                        .HasColumnType("int");

                    b.Property<string>("notes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("menuItemId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DescriptionAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("DescriptionTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("DiscountedPriceAr")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountedPriceEn")
                        .HasColumnType("int");

                    b.Property<int?>("DiscountedPriceTr")
                        .HasColumnType("int");

                    b.Property<int>("ItemOrder")
                        .HasColumnType("int");

                    b.Property<string>("NameAr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NameTr")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PriceAr")
                        .HasColumnType("int");

                    b.Property<int>("PriceEn")
                        .HasColumnType("int");

                    b.Property<int>("PriceTr")
                        .HasColumnType("int");

                    b.Property<int?>("StudentPrice")
                        .HasColumnType("int");

                    b.Property<int?>("categoryId")
                        .HasColumnType("int");

                    b.Property<string>("imageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("isVisible")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("numberOfTimesOrdered")
                        .HasColumnType("int");

                    b.Property<decimal>("ratingValue")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("categoryId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("MenuAppAPI.Models.Order", b =>
                {
                    b.HasOne("MenuAppAPI.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("MenuAppAPI.Models.OrderItems", b =>
                {
                    b.HasOne("MenuAppAPI.Models.Order", null)
                        .WithMany("CustomerOrders")
                        .HasForeignKey("OrderId");

                    b.HasOne("MenuItem", "menuItem")
                        .WithMany()
                        .HasForeignKey("menuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("menuItem");
                });

            modelBuilder.Entity("MenuItem", b =>
                {
                    b.HasOne("MenuAppAPI.Models.Categories", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("categoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MenuAppAPI.Models.Categories", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("MenuAppAPI.Models.Order", b =>
                {
                    b.Navigation("CustomerOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
